services:
  # Service untuk lingkungan PRODUCTION
  # Menjalankan aplikasi yang sudah dicompile dari Dockerfile di atas
  app:
    build:
      context: .
      dockerfile: docker/go.Dockerfile
    image: first-go-api:latest
    container_name: first_go_api_prod
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Service untuk lingkungan DEVELOPMENT
  # Menggunakan 'air' untuk live-reloading
  dev:
    build:
      context: .
      dockerfile: docker/go.dev.Dockerfile
    container_name: first_go_api_dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080" # Gunakan port host yang berbeda agar tidak konflik
  