info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Hello Handler
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Show a hello message
      tags:
      - Hello
swagger: "2.0"
