name: Deploy Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-alpine
      
    steps:

      - name: Log go version
        run: go version

      - name: Install make and curl
        run: apk add --no-cache  make curl

      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Install dependencies
        run: go mod tidy

      - name: Cache go modules
        uses: actions/cache/save@v4
        id: cache
        with:
          path: |
            $HOME/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: make test-verbose

      - name: Build the application
        run: make build

      - name: Run and test application
        run: |
          cd bin && ./main &
          SERVER_PID=$!
          sleep 3
          curl -f http://localhost:8080
          kill $SERVER_PID

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: binary-file
          path: bin
      
      - name: Deploy container
        run: echo "Deploy container logic here"