name: Deploy Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env:
  DEBUG: true
  PORT: 8080

  DB_DRIVER: "mysql"
  DB_HOST: "mysql"
  DB_PORT: 3306
  DB_DATABASE: "first_go_api_db"
  DB_DATABASE_TESTING: "first_go_api_db_test"
  DB_USER: "encang-cutbray"
  DB_PASSWORD: "secret214"
  DB_ROOT_PASSWORD: "secret214"

  CACHE_DRIVER: "redis"
  CACHE_PORT: "6379"
  CACHE_USER: 
  CACHE_PASSWORD: 

  GOOSE_DRIVER: "mysql"
  GOOSE_DBSTRING: "root:secret214@tcp(mysql:3306)/first_go_api_db"
  GOOSE_MIGRATION_DIR: "./pkg/migration"
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.24-alpine

    services:
      mysql:
        image: mariadb:10.6.21
        env:
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
          - "3306:3306"
        volumes:
          - ./docker/mysql:/docker-entrypoint-initdb.d
    steps:
      - name: Log go version
        run: go version

      - name: Install make, curl, and tar
        run: |
          apk add --no-cache make curl tar

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache go modules
        uses: actions/cache/save@v4
        id: cache
        with:
          path: |
            $HOME/.cache/go-build
            /go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod tidy

      - name: Run tests
        run: make test-verbose

      - name: Build the application
        run: make build

      - name: Run and test application
        run: |
          cd bin && ./main &
          SERVER_PID=$!
          sleep 3
          curl -f http://localhost:8080
          kill $SERVER_PID

      - name: Output Step
        run: echo Cached:${{ steps.cache.outputs.cache-hit == 'true'}}

  build:
    needs: test
    runs-on: ubuntu-latest

    container:
      image: golang:1.24-alpine

    steps:
      - name: Log go version
        run: go version

      - name: Install make, curl, and tar
        run: |
          apk add --no-cache make curl tar coreutils

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache go modules
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            $HOME/.cache/go-build
            /go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod tidy

      - name: Build the application
        run: make build

      - name: Check SHA256 of binary
        run: sha256sum bin/main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-file
          path: bin

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Remove old container if exists
        run: |
          docker rm -f first_go_api_prod || true

      - name: Build and Run Production App with Docker Compose
        run: |
          echo $(pwd)
          docker compose -f docker-compose.yml up -d --build app

      - name: Deploy Finished Marker
        run: echo "=== DEPLOYMENT SELESAI ==="

      # - name: Get build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: binary-file
      #     path: bin

      # - name: Check file exists
      #   run: ls -la bin

      # - name: Check SHA256 of binary
      #   run: sha256sum bin/main
