name: Deploy Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-alpine
      
    steps:

      - name: Log go version
        run: go version

      - name: Install make
        run: apk add --no-cache make

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            /go/pkg/mod
            $HOME/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: make test-verbose
      
      - name: Deploy container
        run: echo "Deploy container logic here"