name: Deploy Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-alpine
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log go version
        run: go version

      - name: Install make
        run: apk add --no-cache make


      - name: Cache go modules
        uses: actions/cache/save@v4
        id: cache
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      
      - name: Install dependencizes
        run: make deps

      - name: Run tests
        run: make test-verbose
      
      - name: Deploy container
        run: echo "Deploy container logic here"