name: Development Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Check go version
        run: go version
      - name: Install dependencies
        run: make deps
      - name: Run tests
        run: make test-verbose

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Check go version
        run: go version
      - name: Install dependencies
        run: make deps
      - name: Build the application
        run: make build
      - name: Run and test application
        run: |
          cd bin && ./api &
          SERVER_PID=$!
          sleep 3
          curl -f http://localhost:8080
          kill $SERVER_PID
      - name: Clean bin
        run: make clean


  deploy-to-server:
    needs: test
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build and Run Production App with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build app
          # Tunggu beberapa detik agar service benar-benar up
          sleep 5
          curl -f http://localhost:8080
          docker compose -f docker-compose.yml down