name: Development Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Check go version
        run: go version
      - name: Install dependencies
        run: make deps
      - name: Run tests
        run: make test-verbose

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Check go version
        run: go version
      - name: Install dependencies
        run: make deps
      - name: Build the application
        run: make build
      - name: Run the application and Stop server after 10 seconds
        run: |
          cd bin && ./api &
          SERVER_PID=$!
          sleep 10
          kill $SERVER_PID