name: Merchant Workflow

on:
  workflow_dispatch:
  push:
    branches: [feat/merchant]

env: 
  GUITAR: Fender
  BASS: Ibanez

jobs:
  
  information:
    environment: development
    env:
      GUITAR: ${{vars.GUITAR}}
      PANGGUNG: ${{vars.GUITAR}}
    runs-on: ubuntu-latest
    steps:

      - name: GEAR AT var
        run: echo "I play at ${{vars.PANGGUNG}} with my ${{vars.GUITAR}} guitar and ${{vars.BASS}} bass, ticket ${{secrets.PRICE}}"

      - name: GEAR AT env
        env:
          PANGGUNG: Ancol Beach
        run: echo "I play at ${{env.PANGGUNG}} with my ${{env.GUITAR}} guitar and ${{env.BASS}} bass"
      
      - name: GEAR without curly braces
        run: echo "I play at $PANGGUNG with my $GUITAR guitar and $BASS bass"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create secret directory
        run: mkdir -p secret

      - name: Create .prod.env file from secrets
        run: echo "${{ secrets.PROD_ENV }}" > secret/.prod.env

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-files
          path: secret

  # music:
  #   needs: information
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: The guitar I play
  #       env:
  #         PANGGUNG: GBK Sport Hall
  #       run: echo "I play a ${{env.GUITAR}} guitar and ${{env.BASS}} bass at $PANGGUNG"
