name: Merchant Workflow

on:
  workflow_dispatch:
  push:
    branches: [feat/merchant]

env: 
  GUITAR: Fender

jobs:
  
  information:
    env:
      PANGGUNG: Ancol Beach
      GUITAR: Gibson
    runs-on: ubuntu-latest
    steps:
      - name: Object Github
        run: echo "${{toJSON(github)}}"
      - name: The place I play
        run: echo "I play at ${{env.PANGGUNG}} with my ${{env.GUITAR}} guitar"


  music:
    needs: information
    runs-on: ubuntu-latest
    steps:
      - name: Object Github
        run: echo "${{toJSON(github)}}"
      - name: The guitar I play
        run: echo "I play a ${{env.GUITAR}}"
