name: Merchant Workflow

on:
  workflow_dispatch:
  push:
    branches: [feat/merchant]

env: 
  GUITAR: Fender
  BASS: Ibanez

jobs:
  
  information:
    env:
      PANGGUNG: Ancol Beach
      GUITAR: Gibson
    runs-on: ubuntu-latest
    steps:
      - name: Object Github
        run: echo "${{toJSON(github)}}"

      - name: The place I play
        run: echo "I play at ${{env.PANGGUNG}} with my ${{env.GUITAR}} guitar and ${{env.BASS}} bass"


  music:
    needs: information
    runs-on: ubuntu-latest
    steps:
      - name: The guitar I play
        env:
          PANGGUNG: GBK Sport Hall
        run: echo "I play a ${{env.GUITAR}} guitar and ${{env.BASS}} bass at ${{env.PANGGUNG}}"
